#!/usr/bin/env python3
"""Generate the npm package entry points from icons.json.

Writes ESM and CommonJS builds with the manifest inlined, so consumers never
have to resolve a JSON file or hit the network.

Run from the repository root:

    python3 tools/build_package.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
CDN = "https://cdn.jsdelivr.net/gh/hongyinull/meta-icons@main"

HELPERS = '''
/** Every icon in the set. */
export const icons = ICONS_DATA;

/** CDN base used by {@link url}. */
export const cdn = "CDN_BASE";

/**
 * Icons matching every supplied criterion.
 * @param {{name?: string, slug?: string, style?: string, size?: number,
 *          platform?: string, variant?: string, format?: string}} query
 */
export function filter(query = {}) {
  const keys = Object.keys(query);
  return icons.filter((icon) => keys.every((k) => icon[k] === query[k]));
}

/**
 * The best single match for a name, preferring SVG and the smallest size.
 * @param {string} name
 * @param {{style?: string, size?: number, platform?: string}} [options]
 */
export function find(name, options = {}) {
  const needle = String(name).toLowerCase();
  const hits = icons.filter(
    (icon) =>
      (icon.name === needle || icon.slug === needle || icon.slug.includes(needle)) &&
      Object.entries(options).every(([k, v]) => icon[k] === v)
  );
  if (!hits.length) return undefined;
  const rank = (icon) =>
    (icon.name === needle ? 0 : 1) * 8 +
    (icon.style === "outline" ? 0 : 1) * 4 +
    (icon.format === "svg" ? 0 : 1) * 2;
  return hits.sort(
    (a, b) => rank(a) - rank(b) || a.slug.length - b.slug.length || (a.size ?? 0) - (b.size ?? 0)
  )[0];
}

/**
 * Absolute CDN URL for an icon or icon name.
 * @param {string | {path: string}} icon
 */
export function url(icon) {
  const entry = typeof icon === "string" ? find(icon) : icon;
  return entry ? `${cdn}/${entry.path}` : undefined;
}

/**
 * `<use>` reference into a collection sprite.
 * @param {string | {file: string, platform: string, variant: string, format: string}} icon
 */
export function sprite(icon) {
  const entry = typeof icon === "string" ? find(icon) : icon;
  if (!entry || entry.format !== "svg") return undefined;
  const id = entry.file.replace(/\\.svg$/, "");
  return `${cdn}/sprites/${entry.platform}-${entry.variant}.svg#${id}`;
}

'''

CJS_TAIL = '''
module.exports = { icons, cdn, filter, find, url, sprite };
'''

TYPES = '''export interface Icon {
  /** Base name with style and size stripped, e.g. "heart". */
  name: string;
  /** Full normalised name, e.g. "heart-outline-24". */
  slug: string;
  /** Original Meta filename. */
  file: string;
  /** Repository-relative path. */
  path: string;
  platform: "instagram" | "threads";
  variant: "web" | "ios" | "vector";
  format: "svg" | "png";
  style?: "outline" | "filled";
  /** Nominal size in points. */
  size?: number;
  viewBox?: string;
}

export interface Query {
  name?: string;
  slug?: string;
  style?: Icon["style"];
  size?: number;
  platform?: Icon["platform"];
  variant?: Icon["variant"];
  format?: Icon["format"];
}

export declare const icons: Icon[];
export declare const cdn: string;
export declare function filter(query?: Query): Icon[];
export declare function find(name: string, options?: Query): Icon | undefined;
export declare function url(icon: string | Icon): string | undefined;
export declare function sprite(icon: string | Icon): string | undefined;
'''


def main():
    manifest = json.load(open(os.path.join(ROOT, "icons.json"), encoding="utf-8"))
    data = json.dumps(manifest["icons"], ensure_ascii=False, separators=(",", ":"))
    os.makedirs(DIST, exist_ok=True)

    body = HELPERS.replace("ICONS_DATA", data).replace("CDN_BASE", CDN)
    header = "// Generated by tools/build_package.py — do not edit.\n"

    esm = os.path.join(DIST, "index.mjs")
    open(esm, "w", encoding="utf-8").write(header + body)

    cjs_body = body.replace("export const ", "const ").replace("export function ", "function ")
    cjs = os.path.join(DIST, "index.cjs")
    open(cjs, "w", encoding="utf-8").write(header + cjs_body + CJS_TAIL)

    types = os.path.join(DIST, "index.d.ts")
    open(types, "w", encoding="utf-8").write(TYPES)

    for path in (esm, cjs, types):
        print(f"  {os.path.relpath(path, ROOT):<20} {os.path.getsize(path) / 1024:>6.0f} KB")
    print(f"\n{len(manifest['icons'])} icons inlined")


if __name__ == "__main__":
    main()
